# Table of Contents
 <p><div class="lev2 toc-item"><a href="#はじめに" data-toc-modified-id="はじめに-01"><span class="toc-item-num">0.1&nbsp;&nbsp;</span>はじめに</a></div><div class="lev2 toc-item"><a href="#必要ライブラリの読み込み" data-toc-modified-id="必要ライブラリの読み込み-02"><span class="toc-item-num">0.2&nbsp;&nbsp;</span>必要ライブラリの読み込み</a></div><div class="lev2 toc-item"><a href="#データ準備" data-toc-modified-id="データ準備-03"><span class="toc-item-num">0.3&nbsp;&nbsp;</span>データ準備</a></div><div class="lev1 toc-item"><a href="#Series" data-toc-modified-id="Series-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Series</a></div><div class="lev2 toc-item"><a href="#データ構造" data-toc-modified-id="データ構造-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>データ構造</a></div><div class="lev2 toc-item"><a href="#Series-⇒-他のデータ型" data-toc-modified-id="Series-⇒-他のデータ型-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Series ⇒ 他のデータ型</a></div><div class="lev3 toc-item"><a href="#リスト型" data-toc-modified-id="リスト型-121"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>リスト型</a></div><div class="lev3 toc-item"><a href="#辞書型" data-toc-modified-id="辞書型-122"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>辞書型</a></div><div class="lev3 toc-item"><a href="#タプル" data-toc-modified-id="タプル-123"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>タプル</a></div><div class="lev3 toc-item"><a href="#numpy.array" data-toc-modified-id="numpy.array-124"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>numpy.array</a></div><div class="lev3 toc-item"><a href="#データフレーム" data-toc-modified-id="データフレーム-125"><span class="toc-item-num">1.2.5&nbsp;&nbsp;</span>データフレーム</a></div><div class="lev3 toc-item"><a href="#datetime" data-toc-modified-id="datetime-126"><span class="toc-item-num">1.2.6&nbsp;&nbsp;</span>datetime</a></div><div class="lev2 toc-item"><a href="#他のデータ型　⇒　Series" data-toc-modified-id="他のデータ型　⇒　Series-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>他のデータ型　⇒　Series</a></div><div class="lev3 toc-item"><a href="#リスト" data-toc-modified-id="リスト-131"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>リスト</a></div><div class="lev3 toc-item"><a href="#辞書-※インデックスはソートされる" data-toc-modified-id="辞書-※インデックスはソートされる-132"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>辞書 ※インデックスはソートされる</a></div><div class="lev3 toc-item"><a href="#タプル" data-toc-modified-id="タプル-133"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>タプル</a></div><div class="lev3 toc-item"><a href="#numpy.array" data-toc-modified-id="numpy.array-134"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>numpy.array</a></div><div class="lev3 toc-item"><a href="#データフレーム-※うまくいかない！！！" data-toc-modified-id="データフレーム-※うまくいかない！！！-135"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>データフレーム ※うまくいかない！！！</a></div><div class="lev1 toc-item"><a href="#DataFrame" data-toc-modified-id="DataFrame-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>DataFrame</a></div><div class="lev2 toc-item"><a href="#データ構造" data-toc-modified-id="データ構造-21"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>データ構造</a></div><div class="lev2 toc-item"><a href="#DataFrame-⇒-他のデータ型" data-toc-modified-id="DataFrame-⇒-他のデータ型-22"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>DataFrame ⇒ 他のデータ型</a></div><div class="lev3 toc-item"><a href="#リスト" data-toc-modified-id="リスト-221"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>リスト</a></div><div class="lev3 toc-item"><a href="#辞書" data-toc-modified-id="辞書-222"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>辞書</a></div><div class="lev3 toc-item"><a href="#np.array" data-toc-modified-id="np.array-223"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>np.array</a></div><div class="lev2 toc-item"><a href="#他のデータ型　⇒　DataFrame" data-toc-modified-id="他のデータ型　⇒　DataFrame-23"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>他のデータ型　⇒　DataFrame</a></div><div class="lev3 toc-item"><a href="#リスト" data-toc-modified-id="リスト-231"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>リスト</a></div><div class="lev3 toc-item"><a href="#辞書" data-toc-modified-id="辞書-232"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>辞書</a></div><div class="lev3 toc-item"><a href="#np.array" data-toc-modified-id="np.array-233"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>np.array</a></div>

## はじめに
この資料では、pandasの基本的なデータ型であるSeriesとDataframeについて、<br>
 - 簡単なデータ構造
 - 他のデータ型への変換
 - 他のデータ型からの変換
<br>
を示す

## 必要ライブラリの読み込み

In [1]:
import pandas as pd
import numpy as np

## データ準備

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(
    iris.data, columns=[x[:-5].replace(" ", "_") for x in iris.feature_names])
df["species"] = [iris.target_names[x] for x in iris.target]
df = df[:5]
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# Series

## データ構造

データフレームから1列だけ抽出するとSeriesになる

In [3]:
se = df["sepal_length"][:3]
type(se)

pandas.core.series.Series

listやnumpy.arrayとの違いは、データにインデックスや名前があるところ

In [4]:
se

0    5.1
1    4.9
2    4.7
Name: sepal_length, dtype: float64

要素に少数点がある場合は、中の要素はnumpu.float64で保持される

In [5]:
type(se[0])

numpy.float64

valuesで値が返ってくる

In [6]:
se.values

array([ 5.1,  4.9,  4.7])

index

In [7]:
se.index

RangeIndex(start=0, stop=3, step=1)

文字列型のインデックスを作れる

In [8]:
se.index = ["a", "b", "c"]
se

a    5.1
b    4.9
c    4.7
Name: sepal_length, dtype: float64

## Series ⇒ 他のデータ型

### リスト型 

In [9]:
se_list = se.tolist()
print("type", type(se_list[0]))  # 要素の型はfloat型に変換される（他はそのまま）
se_list

type <class 'float'>


[5.1, 4.9, 4.7]

### 辞書型

In [10]:
se.to_dict()

{'a': 5.0999999999999996, 'b': 4.9000000000000004, 'c': 4.7000000000000002}

### タプル

In [11]:
tuple(se)

(5.0999999999999996, 4.9000000000000004, 4.7000000000000002)

### numpy.array

In [12]:
np.array(se)

array([ 5.1,  4.9,  4.7])

### データフレーム

In [13]:
pd.DataFrame(se)

sepal_length
a           5.1
b           4.9
c           4.7

### datetime

※日付型について、詳しくは『01_データ型_datetime.ipynb』参照

In [14]:
se3 = pd.Series(["2017-07-01", "2017-07-02", "2017-07-03"])
pd.to_datetime(se3)

0   2017-07-01
1   2017-07-02
2   2017-07-03
dtype: datetime64[ns]

## 他のデータ型　⇒　Series

### リスト

In [15]:
pd.Series([1, 2, 3])

0    1
1    2
2    3
dtype: int64

### 辞書 ※インデックスはソートされる

In [16]:
pd.Series({"a": 5.1, "b": 4.9, "c": 4.7})

a    5.1
b    4.9
c    4.7
dtype: float64

### タプル

In [17]:
pd.Series((1, 2, 3))

0    1
1    2
2    3
dtype: int64

### numpy.array

In [18]:
pd.Series(np.array([1, 3, 2]))

0    1
1    3
2    2
dtype: int32

### データフレーム ※うまくいかない！！！

In [19]:
pd.Series(df)

0    (s, e, p, a, l, _, l, e, n, g, t, h)
1       (s, e, p, a, l, _, w, i, d, t, h)
2    (p, e, t, a, l, _, l, e, n, g, t, h)
3       (p, e, t, a, l, _, w, i, d, t, h)
4                   (s, p, e, c, i, e, s)
dtype: object

# DataFrame

## データ構造

In [20]:
type(df)

pandas.core.frame.DataFrame

行列 2重リストやnp.arrayとの違いはindexとcolumnsがあること

In [21]:
df

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

辞書からの作成

In [22]:
pd.DataFrame(
    {
        "a": [1, 2, 3],
        "b": [10.0, 11.5, 5.6],
        "c": ["apple", "banana", "cyber agent"]
    },
    index=[1, 2, 3])

a     b            c
1  1  10.0        apple
2  2  11.5       banana
3  3   5.6  cyber agent

リストからの作成

In [23]:
pd.DataFrame(
    [[1, 2, 3], [10.0, 11.5, 5.6], ["apple", "banana", "cyber agent"]],
    columns=["a", "b", "c"])

a       b            c
0      1       2            3
1     10    11.5          5.6
2  apple  banana  cyber agent

各列のデータ型を確認

In [24]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

index

In [25]:
df.index

RangeIndex(start=0, stop=5, step=1)

columns ※カラムの型はIndex

In [26]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

valuesで中身をarray型で出力する

In [27]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa']], dtype=object)

column変更

In [28]:
df.columns = ["A", "B", "C", "D", "E"]

index変更

In [29]:
df.index = ["a", "b", "c", "d", "e"]
df

A    B    C    D       E
a  5.1  3.5  1.4  0.2  setosa
b  4.9  3.0  1.4  0.2  setosa
c  4.7  3.2  1.3  0.2  setosa
d  4.6  3.1  1.5  0.2  setosa
e  5.0  3.6  1.4  0.2  setosa

## DataFrame ⇒ 他のデータ型

### リスト

In [30]:
list(df.as_matrix().tolist())

[[5.1, 3.5, 1.4, 0.2, 'setosa'],
 [4.9, 3.0, 1.4, 0.2, 'setosa'],
 [4.7, 3.2, 1.3, 0.2, 'setosa'],
 [4.6, 3.1, 1.5, 0.2, 'setosa'],
 [5.0, 3.6, 1.4, 0.2, 'setosa']]

### 辞書

In [31]:
df.to_dict()

{'A': {'a': 5.0999999999999996,
  'b': 4.9000000000000004,
  'c': 4.7000000000000002,
  'd': 4.5999999999999996,
  'e': 5.0},
 'B': {'a': 3.5,
  'b': 3.0,
  'c': 3.2000000000000002,
  'd': 3.1000000000000001,
  'e': 3.6000000000000001},
 'C': {'a': 1.3999999999999999,
  'b': 1.3999999999999999,
  'c': 1.3,
  'd': 1.5,
  'e': 1.3999999999999999},
 'D': {'a': 0.20000000000000001,
  'b': 0.20000000000000001,
  'c': 0.20000000000000001,
  'd': 0.20000000000000001,
  'e': 0.20000000000000001},
 'E': {'a': 'setosa',
  'b': 'setosa',
  'c': 'setosa',
  'd': 'setosa',
  'e': 'setosa'}}

### np.array

In [32]:
df.as_matrix()

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa']], dtype=object)

## 他のデータ型　⇒　DataFrame

### リスト

In [33]:
pd.DataFrame([[1, 2, 3], [10, 20, 30]])

0   1   2
0   1   2   3
1  10  20  30

### 辞書

In [34]:
pd.DataFrame({"A": {"a": 1, "b": 2}, "B": {"a": 3, "b": 4}})

A  B
a  1  3
b  2  4

### np.array

In [35]:
pd.DataFrame(np.array([["a", "b", "c"], [1, 2, 3]]))

0  1  2
0  a  b  c
1  1  2  3